### ISSUE TITLE
Erreur sur la compilation de template .vue en mode watch

### ISSUE THREAD

**Issue by Nalex75** [Thibzzz/Valisette#1]
# What's happening 

Les imports crashent en mode dév depuis des templates .vue

# What's supposed to happen ?

Importer un module normalement.

# Possible fix

Linked to : https://github.com/parcel-bundler/parcel/issues/1563

Ajouter une minification JS sur le mode DEV & WATCH via basics() dans bundler.js

**Comment by Thibzzz** [comment]
fix : ajouter le minify sur le mode dev des temps template .vue
